version: '3'
services:
  go-app:
    build:
      context: .
      dockerfile: ./.Docker/goapp.Dockerfile
    restart: unless-stopped
    image: goapp-devel:latest
    container_name: go-app-devel
    command: make run-docker
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - ./core/database/data/ddl.sql:/docker-entrypoint-initdb.d/10-init.sql
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST=${DATABASE_HOST}
    ports:
      - 5432

volumes:
  postgres: